modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="bindingofminecraft"
version="${file.jarVersion}"
displayName="The Binding of Minecraft"
logoFile="examplemod.png"
credits="Thanks for the game The Binding of Issac."
authors="LTXOM, Wugui, MUZHI"
description='''
//TODO
'''
# This version range declares a minimum of the current minecraft version up to but not including the next major version
#    versionRange="[1.16.5,1.17)"
#    ordering="NONE"
#    side="BOTH"
